-- Default Snowflake profile. Change OLIST_DB.ANALYTICS_MARTS if configured differently.
SELECT * FROM OLIST_DB.ANALYTICS_MARTS.MART_DAILY_REVENUE ORDER BY ORDER_DATE;
SELECT * FROM OLIST_DB.ANALYTICS_MARTS.MART_CUSTOMER_LIFETIME_VALUE ORDER BY CUSTOMER_UNIQUE_ID;
SELECT * FROM OLIST_DB.ANALYTICS_MARTS.MART_SELLER_PERFORMANCE ORDER BY SELLER_ID;
